# Generated by Django 4.1.5 on 2023-01-31 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(blank=True, max_length=25, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='perfil_imagenes')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profie', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
