# Generated by Django 3.2.16 on 2023-01-29 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ECycling', '0005_bicicletas'),
    ]

    operations = [
        migrations.DeleteModel(
            name='bicicletas',
        ),
        migrations.DeleteModel(
            name='indumentaria',
        ),
        migrations.DeleteModel(
            name='venta',
        ),
    ]
