# Generated by Django 4.1.5 on 2023-02-05 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ECycling', '0006_auto_20230129_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='personalizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, null=True)),
                ('imagen_portada', models.ImageField(blank=True, null=True, upload_to='imagen_portada')),
            ],
        ),
    ]
