# Generated by Django 3.2.16 on 2023-01-29 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bicicletas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=60)),
                ('rodado', models.IntegerField(default=0)),
                ('marca', models.CharField(max_length=50, null=True)),
                ('precio', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='indumentaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_indumentaria', models.IntegerField(default=0)),
                ('tipo', models.CharField(max_length=100, null=True)),
                ('genero', models.CharField(max_length=100, null=True)),
                ('nombre', models.CharField(max_length=100, null=True)),
                ('stock', models.IntegerField(default=0)),
                ('precio', models.FloatField(default=0)),
            ],
        ),
    ]
