# Generated by Django 4.1.5 on 2023-01-31 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='indumentaria',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='profile_image'),
        ),
    ]
