# Generated by Django 4.1.5 on 2023-01-31 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_indumentaria_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indumentaria',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='producto_image'),
        ),
    ]
