# Generated by Django 4.1.5 on 2023-02-01 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_alter_indumentaria_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indumentaria',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_productos'),
        ),
    ]
